let westTeamsList = ['Dallas Mavericks', 'Denver Nuggets', 'Golden State Warriors', 'Houston Rockets', 'Los Angeles Clippers', 'Los Angeles Lakers', 'Memphis Grizzlies', 'Minnesota Timberwolves', 'New Orleans Pelicans', 'Oklahoma City Thunder', 'Phoenix Suns', 'Portland Trail Blazers', 'Sacramento Kings', 'Utah Jazz', 'San Antonio Spurs'];
let eastTeamsList = ['Atlanta Hawks', 'Boston Celtics', 'Brooklyn Nets', 'Charlotte Hornets', 'Chicago Bulls', 'Cleveland Cavaliers', 'Detroit Pistons', 'Indiana Pacers', 'Miami Heat', 'Milwaukee Bucks', 'New York Knicks', 'Orlando Magic', 'Philadelphia 76ers','Toronto Raptors', 'Washington Wizards'];
// let teamsLogo = [
//     {TeamName : 'Atlanta Hawks', ImageName : 'atlanta-hawks.svg'},
//     {TeamName : 'Boston Celtics', ImageName : 'boston-celtics.svg'},
//     {TeamName : 'Brooklyn Nets', ImageName : 'brooklyn-nets.svg'},
//     {TeamName : 'Charlotte Hornets', ImageName : 'charlotte-hornets.svg'},
//     {TeamName : 'Chicago Bulls', ImageName : 'chicago-bulls.svg'},
//     {TeamName : 'Cleveland Cavaliers', ImageName : 'cleveland-cavaliers.svg'},
//     {TeamName : 'Dallas Mavericks', ImageName : 'dallas-mavericks.svg'},
//     {TeamName : 'Denver Nuggets', ImageName : 'denver-nuggets.svg'},
//     {TeamName : 'Detroit Pistons', ImageName : 'detroit-pistons.svg'},
//     {TeamName : 'Golden State Warriors', ImageName : 'golden-state-warriors.svg'},
//     {TeamName : 'Houston Rockets', ImageName : 'houston-rockets.svg'},
//     {TeamName : 'Indiana Pacers', ImageName : 'indiana-pacers.svg'},
//     {TeamName : 'Los Angeles Clippers', ImageName : 'los-angeles-clippers.svg'},
//     {TeamName : 'Los Angeles Lakers', ImageName : 'los-angeles-lakers.svg'},
//     {TeamName : 'Memphis Grizzlies', ImageName : 'memphis-grizzlies.svg'},
//     {TeamName : 'Miami Heat', ImageName : 'miami-heat.svg'},
//     {TeamName : 'Milwaukee Bucks', ImageName : 'milwaukee-bucks.svg'},
//     {TeamName : 'Minnesota Timberwolves', ImageName : 'minnesota-timberwolves.svg'},
//     {TeamName : 'New Orleans Pelicans', ImageName : 'new-orleans-pelicans.svg'},
//     {TeamName : 'New York Knicks', ImageName : 'new-york-knicks.svg'},
//     {TeamName : 'Oklahoma City Thunder', ImageName : 'oklahoma-city-thunder.svg'},
//     {TeamName : 'Orlando Magic', ImageName : 'orlando-magic.svg'},
//     {TeamName : 'Philadelphia 76ers', ImageName : 'philadelphia-76ers.svg'},
//     {TeamName : 'Phoenix Suns', ImageName : 'phoenix-suns.svg'},
//     {TeamName : 'Portland Trail Blazers', ImageName : 'portland-trail-blazers.svg'},
//     {TeamName : 'Sacramento Kings', ImageName : 'sacramento-kings.svg'},
//     {TeamName : 'San Antonio Spurs', ImageName : 'san-antonio-spurs.svg'},
//     {TeamName : 'Toronto Raptors', ImageName : 'toronto-raptors.svg'},
//     {TeamName : 'Utah Jazz', ImageName : 'utah-jazz.svg'},
//     {TeamName : 'Washington Wizards', ImageName : 'washington-wizards.svg'},
// ];